package it.polimi.ingsw.view.gui;

import it.polimi.ingsw.model.tools.MORLogger;
import it.polimi.ingsw.observer.ViewObservable;
import it.polimi.ingsw.observer.ViewObserver;
import it.polimi.ingsw.view.gui.controllers.SceneController;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;

import java.io.IOException;
import java.util.List;

/**
 * Static utilities for the GUI interface.
 */
public class GuiSceneUtils {
    private static Scene activeScene;

    /**
     * Returns the current scene.
     * @return The active scene.
     */
    public static Scene getActiveScene(){
        return activeScene;
    }

    /**
     * Changes the current active panel
     * @param observerList Observers for the current panel to be transferred.
     * @param scene The scene in which you want your panel to be displayed.
     * @param fxmlSource The fxml file you want to load
     * @param <T> The type of the controller you want back.
     * @return The generated controller for the scene.
     */
    public static <T> T changeActivePanel(List<ViewObserver> observerList, Scene scene, String fxmlSource){
        T controller = null;
        try {
            FXMLLoader loader = new FXMLLoader(SceneController.class.getResource("/fxml/" + fxmlSource));
            Parent root = loader.load();
            controller = loader.getController();
            ((ViewObservable) controller).addAllObservers(observerList);

            activeScene = scene;
            activeScene.setRoot(root);
        } catch(IOException e){
            MORLogger.LOGGER.severe("Could not load the scene from file! Game will end!");
            System.exit(1);
        }
        return controller;
    }

    /**
     *  Changes the current active panel in the active scene.
     * @param observerList Observers for the current panel to be transferred.
     * @param fxmlSource The fxml file you want to load
     * @param <T> The type of the controller you want back.
     * @return The generated controller for the scene.
     */
    public static <T> T changeActivePanel(List<ViewObserver> observerList, String fxmlSource){
        return changeActivePanel(observerList, activeScene, fxmlSource);
    }

    /**
     * Shows a generic alert window
     * @param severity The severity of the alert
     * @param title The title you want to display.
     * @param message The message text.
     */
    public static void showAlertWindow(AlertType severity, String title, String message){
        Alert alertWindow = new Alert(severity, message);
        alertWindow.setTitle(title);
        alertWindow.setHeaderText(title);
        alertWindow.setResizable(false);
        alertWindow.initOwner(activeScene.getWindow());
        alertWindow.showAndWait();
    }

    /**
     * Checks if the supply event is generated by pressing enter.
     * @param keyEvent The {@code KeyEvent} you want to check
     * @return {@code true} if the Enter key has been pressed, {@code false} otherwise.
     */
    public static boolean isAnEnterKeyEvent(KeyEvent keyEvent){
        return keyEvent.getCode() == KeyCode.ENTER;
    }
}
